Corsafe-Disease-Predictor/DiseasePredictor/DiseasePredictor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from MainApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_page),
    url('^Doctor/', include('Doctor.urls', namespace = 'Doctor')),
    url('^Diseases/', include('Diseases.urls', namespace = 'Diseases')),
    url('^Main/', include('MainApp.urls', namespace = 'MainApp')),
]

from . import settings
from django.contrib.staticfiles.urls import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Corsafe-Disease-Predictor/DiseasePredictor/Diseases/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "Diseases"

urlpatterns = [
        path("input/", views.input_view, name="Input"),
        ]

Corsafe-Disease-Predictor/DiseasePredictor/MainApp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'MainApp'

urlpatterns = [
        url('^about/$', views.about_page , name="About")
        ]

Corsafe-Disease-Predictor/DiseasePredictor/Diseases/models.py
from django.db import models

class Symptom_List(models.Model):

    symptom1 = models.CharField(max_length=256 , blank = True)
    symptom2 = models.CharField(max_length=256 , blank = True)
    symptom3 = models.CharField(max_length=256 , blank = True)
    symptom4 = models.CharField(max_length=256 , blank = True)
    symptom5 = models.CharField(max_length=256 , blank = True)
    symptom6 = models.CharField(max_length=256 , blank = True)
    symptom7 = models.CharField(max_length=256 , blank = True)

Corsafe-Disease-Predictor/DiseasePredictor/MainApp/models.py
from django.db import models

# Create your models here.

Corsafe-Disease-Predictor/DiseasePredictor/Diseases/forms.py
from django import forms
from . import models

class Symptom_Form(forms.ModelForm):

    class Meta:
        model = models.Symptom_List
        fields = '__all__'
        widgets = {
                'symptom1' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                'symptom2' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                'symptom3' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                'symptom4' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                'symptom5' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                'symptom6' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                'symptom7' : forms.TextInput(attrs = { 'class' : 'field' , 'hidden':True }),
                }

Corsafe-Disease-Predictor/DiseasePredictor/Diseases/views.py
from django.shortcuts import render
from . import forms
import pickle
from DiseasePredictor import settings
import os

BASE_DIR = settings.BASE_DIR
common = pickle.load(open(os.path.join(BASE_DIR,'media','data','common.p'), "rb"))
uncommon = pickle.load(open(os.path.join(BASE_DIR,'media','data','uncommon.p'), "rb"))
all_ordered = pickle.load(open(os.path.join(BASE_DIR,'media','data','all_ordered.p'), "rb"))

def input_view(request):

    if request.method=="POST":

        symptoms_form = forms.Symptom_Form(data = request.POST)
        if symptoms_form.is_valid():
            disease_prediction = ml(symptoms_form.cleaned_data)
            print(symptoms_form.cleaned_data)
            if len(disease_prediction)==1:
                return render(request, "result.html", {'multiple': 0, 'prognosis': disease_prediction[0][0]})
            else:
                return render(request, "result.html", {'multiple': 1, 'prognosis': disease_prediction})
        
        return render(request, "something_wrong.html", {'message' : "Something went wrong!"})
    
    return render(request, "input.html",{'form': forms.Symptom_Form, 'common': common,'uncommon':uncommon, 'length':7})




def ml(clean_data):
    values_1 = [ i for i in clean_data.values() ]
    l = [ all_ordered[i] for i in values_1 if i!='' ]
    
    test_list = [ 0 for i in range(132) ]
    for i in l :
        test_list[i] = 1
    
    model = None
    label_coder = None
    # with open('media/models/model_rf.sav', 'rb') as fp:
    with open('media/models/model_rf_64.sav', 'rb') as fp:
        model = pickle.load(fp)
    # with open('media/models/label_coder.sav', 'rb') as fp:
    with open('media/models/label_coder_64.sav', 'rb') as fp:
        label_coder = pickle.load(fp)
    ls = []
    threshold = 15

    result = model.predict_proba([test_list])
    for i in range(0,len(result[0])):
        if result[0][i]!=0:
            ls.append((label_coder.inverse_transform([i,]),(result[0][i]*100)))

    ls = sorted([ (i[0][0],int(i[1])) for i in ls if i[1]>=threshold ] , reverse=True, key=lambda x: x[1])
    if ls[0][1]<threshold:
        return ls[0]
    else:
        return ls

Corsafe-Disease-Predictor/DiseasePredictor/MainApp/views.py
from django.shortcuts import render

def home_page(request):

    return render(request, "home.html", {})

def about_page(request):
    return render(request, "about.html", {})

Corsafe-Disease-Predictor/DiseasePredictor/media/templates/home.html
<!DOCTYPE html>
<html>
   <head>
      <title>About</title>
      <style>
          body{
             background: url("https://image.freepik.com/free-photo/young-handsome-physician-medical-robe-with-stethoscope_1303-17818.jpg") ;
             background-repeat: no-repeat;
             background-size: cover;
	  }
	  .nav{
	background-color:#26232e;
	color:white;
	margin: 20px;
	margin-top: 50px ;
	border-radius: 25px;
	padding: 10px;
	font-size:1.5rem;
	text-align: center;
	word-spacing: 40px;
	box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
	font-family: 'Ubuntu', sans-serif;
	}
	a:link{
        text-decoration: none;
        color:white;
	}
	a:visited{
        text-decoration: none;
        color:gray;
	}
	a:hover{
        color:yellow;
	}
	.l1{
	display: inline;
	}

      </style>
      <body>
<div class="nav">

	   <nav>
        	      <ul>
		      <li class="l1"><a href='{% url "Diseases:Input" %}'>Prognosis</a></li>
			
	              </ul>
	  </nav>
</div>
<br><br><br><br>
      <h1 style="font-size:60px; font-family:'Ubuntu',sans-serif;margin-right:30px;line-height: 0.5;">&nbsp Welcome to</h1>
	  <h1 style="font-size:80px; font-family:'Ubuntu',sans-serif;margin-right:30px;line-height:0;">&nbspCorsafe-Disease <span style="color:red;">Predictor</span>!</h1>
      </body>
</html>

Corsafe-Disease-Predictor/DiseasePredictor/media/templates/input.html
<!DOCTYPE html>
<html>
   <head>
      <title>Input page</title>
   <script type ="text/javascript" src="/media/js/jquery.js"></script>
   <script type ="text/javascript" src="/media/js/dropper.js"></script>
      <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
      <style>
          body{
          background-color:#59405c;
          }
          .div2{
          background-color:white;
          margin: 20px;
          margin-top: 50px ;
          margin-left : 5 px;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          position: fixed;
          float :right;
          right:0px;
          width:20%;              }
         .nav{
          background-color:white;
          margin: 20px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
              }
          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          float:left;
          width: 70%;
          position:sticky;
          }
          .textbox{
          border:3px solid red;
          font-size: 20px;
          border-radius: 2px;
          text-align: center;
          }
          .button1{
          border-color: rgb(10, 200, 10);
          color: black;
          font-family: 'Ubuntu', sans-serif;
          border-radius: 20px;
          font-size: 15px;
          padding :5px;
          }
            .symptoms{
               border-radius:25px;
               color:white;
             display:inline-block;
            border:1px solid #CCC;
            box-shadow: 0 0 5px -1px rgba(0,0,0,0.8);
            vertical-align:middle;
            padding: 10px;
            margin: 5px;
            text-align: center;
          }
          .c{
          background-color:green;
          text-color:red;
          }
          .uc{
          background-color:blue;
          text-color:green;
          }
      </style>
   </head>
   <body>
	   {% include "menu-template.html" %}
           <form method="POST" id="target-form" hidden>
         {% csrf_token %}
         {{ form }}
      </form>
      <div class="div1">
      <div class="main-div">
         <h1>Prognosis Analyser</h1>
         <h3 align="left">&nbsp&nbsp Steps to follow:</h3>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 1.Drag and drop symptoms to the box and submit it to run the analysis.</p>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 2.You can submit a maximum of 7 symptoms</p>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 3.To remove a symptom,please drag it back to its original location</p>
         <p align="left">&nbsp&nbsp&nbsp&nbsp 4.In case of any error, try refreshing the page.</p>
         <div class = "section" id = "options" ondragover='allowDrop(event);' ondrop='drop2(event);'>
            <h3 align="left">&nbsp&nbsp Common:</h3> <br>
            <div id="common">
            {% for i in common %}
               <div id='{{ i }}' class = "symptoms noDrop c " draggable='true' ondragstart='drag(event);'>
                  {{ i }}
               </div>
            {% endfor %}
            </div>
            <h3 align="left">&nbsp&nbsp Uncommon:</h3> <br>
            {% for i in uncommon %}
               <div id='{{ i }}' class ="symptoms noDrop uc"  draggable='true' ondragstart='drag(event);'>
                  {{ i }}
               </div>
            {% endfor %}
            <br>
         </div>
         <br>
      </div>
      </div>
      <div class="div2">         
	      <div class = "section"  id = "selections"  ondragover='allowDrop(event);' ondrop='drop1(event);'>
            <h3>Drop your symptoms here</h3>
            <h3>(Maximum {{ length }} symptoms)</h3><br>
         <br>
         <br>
         </div>
         <br>
         <button class="button1" id = "submit">Submit</button>
      </div>
   </body>
</html>

Corsafe-Disease-Predictor/DiseasePredictor/media/templates/menu-template.html
<style>
 .nav{
	background-color:#26232e;
	color:white;
	margin: 20px;
	margin-top: 50px ;
	border-radius: 25px;
	padding: 10px;
	font-size:1.5rem;
	text-align: center;
	word-spacing: 40px;
	box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
	font-family: 'Ubuntu', sans-serif;
	}
a:link{
        text-decoration: none;
        color:white;
}
a:visited{
        text-decoration: none;
        color:white;
}
a:hover{
        color:yellow;
}
.l1{
            display: inline;
}
</style>
<div class="nav noDrop">
   <nav>
              <ul>
              <li class="l1"><a href="/">Home</a></li>
              </ul>
  </nav>
</div>

Corsafe-Disease-Predictor/DiseasePredictor/media/templates/message.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ header }}</title>
	</head>
	<body>
		{% include "menu-template.html" %}
		<h3>{{ message }}!</h3>
	</body>
</html>

Corsafe-Disease-Predictor/DiseasePredictor/media/templates/result.html
<!DOCTYPE html>
<html>
   <head>
      <title>Analysis Page</title>
      <style>
          body{
          background-color:  #59405c;
          }
         .nav{
          background-color:white;
          margin: 20px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          word-spacing: 40px;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
              }
              a:link{
            text-decoration: none;
            color:white;
            }
            a:visited{
            text-decoration: none;
            color:white;
            }
            a:hover{
            color:yellow;
            }
              .l1{
                display: inline;
             }          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          }
          .div2{
           background-color : rgba(200, 10, 10, 0.2);
           font-family: 'Ubuntu', sans-serif;
           font-size:18px;
          }      </style>
   </head>
   <body>
		{% include "menu-template.html" %}
           <div class="div1">
            <h1>Analysis Result</h1>
            <div align="left">
             <h3><b>&nbsp&nbsp Here is our analysis report:</b></h3>
		{% if multiple %}
		Multiple prognosis detected<br><br>
		<table id="multiResult">
			<thead>
				<td>Prognosis</td>
				<td>Percentage(%)</td>
			</thead>
			<tbody>
				{% for i,j in prognosis %}
				<tr>
					<td>{{ i }}</td>
					<td>{{ j }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<br>
		**rest of the results ommited due to low probability
		{% else %}
                <ul>
			<li style="font-size:20px">{{ prognosis }}</li>
                </ul>
		{% endif %}
                <div class="div2">
                    <p><b> &nbsp&nbsp Note:&nbsp This is a completely computer generated prognosis report! Please do not consider this as a final report.Consult a doctor before taking medicine.</b></p>                </div>
            </div>        </div>
   </body>
</html>

Corsafe-Disease-Predictor/DiseasePredictor/media/templates/something_wrong.html
<!DOCTYPE html>
<html>
   <head>
	   <title>{{ title }}</title>
      <style>
            body{
		    background-color: #1164b4;
            }
          .div1{
          background-color:white;
          margin: 20px;
          margin-right: 5px;
          margin-top: 50px ;
          border-radius: 25px;
          padding: 10px;
          text-align: center;
          box-shadow: 0px 5px 20px rgba(0,0,0,0.5);
          font-family: 'Ubuntu', sans-serif;
          }      </style>
   </head>
   <body>
	   {% include "menu-template.html" %}
      <div class="div1">
	      <h1>{{ heading }}</h1>
	      <p>{{ message }}</p>
        </div>
   </body>
</html>